# Generated by Django 4.2.1 on 2023-12-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='DataTest',
        ),
    ]
